accessskeyid: 4107B3xxxxCE99A1C781xxxx59
accesskeysecret: 8877CxxxxxEB5738EFxxx0201C9
pollinginterval: 40
vips: 
- 10.0.0.30
- 10.0.0.11
- 10.0.0.21
- 192.168.1.50
allnetworkinterfaces: 
- rangid: cn-east-2
  networkinterfaceid: likeport-fet9c4pvzt
- rangid: cn-east-2
  networkinterfaceid: likeport-pig3p7864x

localnetworkinterface: 
  rangid: cn-east-2
  networkinterfaceid: likeport-fet9c4pvzt

